# Generated by Django 5.1.7 on 2025-06-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanNmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=50)),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanWhatweb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('result', models.CharField(max_length=255)),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanZap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alert', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=20)),
                ('confidence', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('reference', models.URLField()),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
